### ISSUE TITLE
[autonity] Helm upgrade fail due to init-job

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose-helm3#81]
## Workaround
- Remove job manually before upgrade

**Comment by Klazomenai** [comment]
@eastata This migrated issue looks to have been resolved by the issue: [[autonity] Cleanup old resources from potentially failed installs #74](https://github.com/clearmatics/charts-ose-helm3/issues/74). This issue was resolved before migration of issues from the `charts-ose` chart. Can you confirm that #74 did indeed resolve this issue.

**Comment by eastata** [comment]
Looks like duplicate issue
