### ISSUE TITLE
Improve repo reliability

### ISSUE THREAD

**Issue by eastata** [clearmatics/charts-ose-helm3#85]
- [ ] Add replications for `S3 bucket`
- [ ] Add backup
- [ ] Add monitoring and alerting

**Comment by Klazomenai** [comment]
Closing this as won't fix. Replication and backups not required for generated artefacts because artefacts can always get re-generated if the bucket storage becomes problematic. Monitoring and alerting not required at this level as alerting will be performed at the push stage from the GitHub action generating the push. Any production grade repository requirements will follow through from JFrog.
